---
title: "Regression from A to Z"
output:
  html_document:
    df_print: paged
---

```{r include=FALSE}
library(car)
library(DT)
```


# Week 1:  Back to Basics

```{r}
pet <- c(rep("dog",6),rep("cat",5), rep("fish", 4), rep("rat",3))
str(pet)
pet.f <- as.factor(pet)
y <- rnorm(length(pet))
df <- data.frame(y,pet,pet.f)
str(df)
#contrasts(pet) # don't run - returns an error
contrasts(pet.f)





```

# Week 2:  Rolling up our sleeves

```{r}
N <- 250
x1 <- rnorm(N, 50, 3)
x2 <- rnorm(N, 10, 2)
x3 <- rnorm(N)
x4 <- rnorm(N, 0, 10) + x1 + x2 + x3

y1 <- x1 + x2 + x3 + rnorm(N, 0, 10)
y2 <- x3 + rnorm(N)
y3 <- x1 + x2 + x3 + x4 + rnorm(N, 0, 10)

df <- data.frame(y1, y2, y3, x1, x2, x3, x4)

lm1 <- lm(y2~x3,df)
lm2 <- lm(y1~x1+x2+x3+x4, df)
lm3 <- lm(y3~x1+x2+x3+x4, df)

# Cohen and Cohen r^2 = .25

x <- rnorm(N)
var(x)
y <- x + rnorm(N,0,sqrt(3))
var(y)
lm4 <- lm(y~x)
summary(lm4)



```

# Week 3:  Doing the basics

```{r}

## continue with model 4 from above
x <- rnorm(N)
var(x)
y <- x + rnorm(N,0,sqrt(3))
var(y)
lm4 <- lm(y~x)
summary(lm4)

## R^2 is just the correlation between y observed and y predicted

y.hat <- predict(lm4)
cor(y,y.hat)
round(cor(y,y.hat)^2,4)

var(predict(lm4))/var(y)
sd(resid(lm4))
mean(resid(lm4))

var(y)
var(predict(lm4))
var(resid(lm4))

var(predict(lm4)) + var(resid(lm4))


# standard error of estimate
sd(resid(lm4))
plot(lm4)

x.bad <- x
str(x.bad)
max(x.bad)

length(x.bad)

newval <- runif(4, 5, 10)
rownewval <- runif(4,1,250)

x.bad[rownewval] <- newval

lm4.bad <- lm(y~x.bad)
summary(lm4)
summary(lm4.bad)



plot(lm4.bad)

df.bad <- data.frame(y,x,x.bad)
df.fixed <- df.bad[-c(rownewval),]

lm4.fixed <- lm(y~x.bad,data=df.fixed)
summary(lm4.fixed)
plot(lm4.fixed)
```

# Week 4

```{r}

# see week 3

foo <- gl(5,50)
str(foo)

test <- df.bad[order(df.bad$y),]
str(test)
test$foo <- foo
lm5 <- lm(y~foo,test)
summary(lm5)

round(aggregate(test$y, by=list(test$foo), mean),2)

levels(test$foo)
contrasts(test$foo)

```

Testing...123...testing